name: Build APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Download repository
      uses: actions/checkout@v4

    - name: Prepare HTML
      run: |
        mkdir -p app/src/main/assets
        cp index.html app/src/main/assets/index.html

    - name: Create APK file
      run: |
        mkdir output
        zip -r output/app.apk app

    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: apk
        path: output/app.apk
